name       : nautilus-python
version    : 1.2.2
release    : 7
homepage   : https://wiki.gnome.org/Projects/NautilusPython
source     :
    - https://download.gnome.org/sources/nautilus-python/1.2/nautilus-python-1.2.2.tar.xz : 90cda3fd613ed012214e47c2dc6f814db4e204a5af38e840479819ab9c59f112
license    : GPL-2.0-only
component  : desktop
summary    : Nautilus-python enables Python extentions in Nautilus
description: |
    These are unstable bindings for the nautilus extension library introduced in Gnome 2.6.
builddeps  :
    - pkgconfig(libnautilus-extension)
    - pkgconfig(pygobject-3.0)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
