name       : nautilus-python
version    : '4.0'
release    : 16
homepage   : https://wiki.gnome.org/Projects/NautilusPython
source     :
    - https://download.gnome.org/sources/nautilus-python/4.0/nautilus-python-4.0.tar.xz : 17243d62eb7d7d839a9461ab8d0701688805c7161a6705e61413a58ec268281a
license    : GPL-2.0-only
component  : desktop
summary    : Nautilus-python enables Python extentions in Nautilus
description: |
    These are unstable bindings for the nautilus extension library introduced in Gnome 2.6.
builddeps  :
    - pkgconfig(libnautilus-extension-4)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
