name       : nautilus-python
version    : 1.2.3
release    : 10
homepage   : https://wiki.gnome.org/Projects/NautilusPython
source     :
    - https://download.gnome.org/sources/nautilus-python/1.2/nautilus-python-1.2.3.tar.xz : 073ce0297282259937ab473d189b97a04f42b97197c9292fc3bde9d135282098
license    : GPL-2.0-only
component  : desktop
summary    : Nautilus-python enables Python extentions in Nautilus
description: |
    These are unstable bindings for the nautilus extension library introduced in Gnome 2.6.
builddeps  :
    - pkgconfig(libnautilus-extension)
    - pkgconfig(pygobject-3.0)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
