name       : nautilus-python
version    : 1.1
release    : 3
homepage   : http://gnome.org
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/nautilus-python/1.1/nautilus-python-1.1.tar.xz : 7825e08ada8e131f829d0e7d4144dcfac9fad7bfd7c0600bf3985349c20c496b
license    : GPL-2.0
component  : desktop
summary    : Nautilus-python enables Python extentions in Nautilus
description: |
    These are unstable bindings for the nautilus extension library introduced in Gnome 2.6.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - pkgconfig(libnautilus-extension)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
